[env]
PULUMI_ROOT = "{{env.PWD}}/.root"

_.path = [
  "{{env.PULUMI_ROOT}}/bin",
]

[tools]
changie = "latest"
cue = "v0.12.0"
go = "1.25.7"
golangci-lint = "2.5.0"
jq = "latest"
pulumi = "latest"
"ubi:pulumi/pulumictl" = "latest"

[plugins]
